### PR TITLE
[SQL] Improvements in JIT code generation

### LINKED ISSUE #175: `Date` deserialization is broken.
This [code](https://github.com/feldera/dbsp/blob/0211b620d0ef441b2ded6c72ae5da6f845a38c4c/sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs#L589) in `sqllib/src/timestamp.rs` doesn't parse dates correctly. I have a [repro](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ed6623ca278bfe74d1e4753601789c39) in the playground.

Changing `NaiveDateTime` to `NaiveDate` seems to fix it.

@gz

### PR DESCRIPTION
**Pull request by mihaibudiu**
Also fixes #175

### CODE REVIEW

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/JitTests.java [hunk 1]
```diff
@@ -142,33 +102,6 @@ public void groupByCountTest() {
...
-    @Test @Override @Ignore("Runtime memory allocation error https://github.com/feldera/dbsp/issues/145")
-    public void joinNullableTest() {
-        String query = "SELECT T1.COL3, T2.COL3 FROM T AS T1 JOIN T AS T2 ON T1.COL1 = T2.COL5";
-        this.testQuery(query, empty);
-    }
-
-    @Test @Override @Ignore("Runtime memory allocation error https://github.com/feldera/dbsp/issues/145")
-    public void joinTest() {
-        String query = "SELECT T1.COL3, T2.COL3 FROM T AS T1 JOIN T AS T2 ON T1.COL1 = T2.COL1";
-        this.testQuery(query, new DBSPZSetLiteral.Contents(
```
Comment (lalithsuresh) [inline sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/JitTests.java:165]: Are these tests no longer needed?

**Comment by mihaibudiu** [comment]
I will wait for #197 to be merged to check which tests still fail.
