### PR TITLE
[JIT] Misc improvements

### LINKED ISSUE #128: [JIT] panic in facade.rs for circuit with unused input
Here is a Rust program that causes a panic:
`thread 'test0' panicked at 'called `Option::unwrap()` on a `None` value', /home/mbudiu/.cargo/git/checkouts/dbsp-0cbfb4410f21b1d3/c09f17a/crates/dataflow-jit/src/facade.rs:132:60`

Unfortunately I am not sure how to give a simpler reproduction, since this is also about the testing code generated:

```
// Automatically-generated file
#![allow(dead_code)]
#![allow(non_snake_case)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use dbsp::{
    algebra::{ZSet, MulByRef, F32, F64, Semigroup, SemigroupValue,
    UnimplementedSemigroup, DefaultSemigroup},
    circuit::{Circuit, Stream},
    operator::{
        Generator,
        FilterMap,
        Fold,
        time_series::{RelRange, RelOffset, OrdPartitionedIndexedZSet},
        MaxSemigroup,
        MinSemigroup,
    },
    trace::ord::{OrdIndexedZSet, OrdZSet},
    zset,
    DBWeight,
    DBData,
    DBSPHandle,
    Runtime,
};
use dbsp_adapters::Catalog;
use genlib::*;
use size_of::*;
use ::serde::{Deserialize,Serialize};
use compare::{Compare, Extract};
use std::{
    convert::identity,
    fmt::{Debug, Formatter, Result as FmtResult},
    cell::RefCell,
    path::Path,
    rc::Rc,
    marker::PhantomData,
    str::FromStr,
};
use dataflow_jit::{
    sql_graph::SqlGraph,
    ir::{
        GraphExt,
        NodeId,
        Constant,
        literal::{
            StreamCollection::Set,
            NullableConstant,
            RowLiteral,
            NullableConstant::{Nullable, NonNull},
        },
    },
    facade::{DbspCircuit,Demands},
    codegen::CodegenConfig,
};
use rust_decimal::Decimal;
use tuple::declare_tuples;
use sqllib::{
    casts::*,
    geopoint::*,
    timestamp::*,
    interval::*,
};
use sqllib::*;
use sqlvalue::*;
use hashing::*;
use readers::*;
use sqlx::{AnyConnection, any::AnyRow, Row};

type Weight = i64;
declare_tuples! {
}


#[test]
pub fn test0() {
    /* 
    6887 Source()
    6914 Constant()
        [0i32]
    6915 Sink(6914)
     */
    const CIRCUIT: &str = "{\n  \"nodes\" : {\n    \"6887\" : {\n      \"Source\" : {\n        \"layout\" : 1,\n        \"table\" : \"T\"\n      }\n    },\n    \"6914\" : {\n      \"ConstantStream\" : {\n        \"comment\" : \"{ Tuple1::new(0i32) => 1}\",\n        \"layout\" : {\n          \"Set\" : 2\n        },\n        \"value\" : {\n          \"layout\" : {\n            \"Set\" : 2\n          },\n          \"value\" : {\n            \"Set\" : [ [ {\n              \"rows\" : [ {\n                \"NonNull\" : {\n                  \"I32\" : 0\n                }\n              } ]\n            }, 1 ] ]\n          }\n        },\n        \"consolidated\" : false\n      }\n    },\n    \"6915\" : {\n      \"Sink\" : {\n        \"input\" : 6914,\n        \"comment\" : \"CREATE VIEW V AS SELECT 0\"\n      }\n    }\n  },\n  \"layouts\" : {\n    \"1\" : {\n      \"columns\" : [ {\n        \"nullable\" : false,\n        \"ty\" : \"I32\"\n      }, {\n        \"nullable\" : false,\n        \"ty\" : \"F64\"\n      }, {\n        \"nullable\" : false,\n        \"ty\" : \"Bool\"\n      }, {\n        \"nullable\" : false,\n        \"ty\" : \"String\"\n      }, {\n        \"nullable\" : true,\n        \"ty\" : \"I32\"\n      }, {\n        \"nullable\" : true,\n        \"ty\" : \"F64\"\n      } ]\n    },\n    \"2\" : {\n      \"columns\" : [ {\n        \"nullable\" : false,\n        \"ty\" : \"I32\"\n      } ]\n    }\n  }\n}";
    let graph = serde_json::from_str::<SqlGraph>(CIRCUIT).unwrap().rematerialize();
    let graph_nodes = graph.nodes();
    let mut demands = Demands::new();
    let T_id = NodeId::new(6887u32);
    let T_layout = (graph_nodes[&T_id]).clone().unwrap_source().layout();
    let mut circuit = DbspCircuit::new(graph, true, 1usize, CodegenConfig::debug(), demands);
    circuit.append_input(T_id, &Set(vec!(
        (RowLiteral::new(vec!(
            NonNull(Constant::I32(10i32)), NonNull(Constant::F64(1.0)), NonNull(Constant::Bool(false)), NonNull(Constant::String(String::from("Hi"))), Nullable(Some(Constant::I32(1i32))), Nullable(Some(Constant::F64(0.0))), )), 1i32, ), (RowLiteral::new(vec!(
            NonNull(Constant::I32(10i32)), NonNull(Constant::F64(12.0)), NonNull(Constant::Bool(true)), NonNull(Constant::String(String::from("Hi"))), NullableConstant::null(), NullableConstant::null(), )), 1i32, ), )));
    circuit.step().unwrap();
    let V = circuit.consolidate_output(NodeId::new(6915u32));
    assert!(must_equal_sc(&V, &Set(vec!(
        (RowLiteral::new(vec!(
            NonNull(Constant::I32(0i32)), )), 1i32, ), ))));
    circuit.kill().unwrap();
}
```

### PR DESCRIPTION
**Pull request by Kixiron**
- Bedrock for string parsing
- Fixed dead sources/sinks panicking (fixes #128)
- Added `.consolidate()`/`.to_consolidated()` methods to `StreamCollection` (addresses #125, if comparing two possibly non-consolidated `StreamCollections` you can consolidate and compare them)
- Adds an `input_layout: StreamLayout` field to `Sink`s (cc @mihaibudiu for json changes), new json will look like this
  ```json
  "Sink": {
    "input": 1,
    "input_layout": { "Set": 2 }
  }
  ```

### CODE REVIEW

File: crates/dataflow-jit/src/codegen/call.rs [hunk 1]
```diff
@@ -1173,6 +1175,103 @@ impl CodegenCtx<'_> {
...
+            ret_ty.size(&self.frontend_config()),
+        ));
+        let slot_ptr = builder.ins().stack_addr(self.pointer_type(), slot, 0);
+
+        let intrinsic = self.imports.get(intrinsic, self.module, builder.func);
+        let errored = builder.call_fn(intrinsic, &[ptr, length, slot_ptr]);
+
+        // FIXME: We should return a two-valued struct to allow users to handle
+        // failed parsing, which is super expected
+        builder.ins().trapnz(errored, TRAP_FAILED_PARSE);
```
Comment (mihaibudiu) [inline crates/dataflow-jit/src/codegen/call.rs:1268]: I think that in general failed parsing will return NULLs in SQL.

File: crates/dataflow-jit/src/ir/literal.rs [hunk 2]
```diff
@@ -73,9 +84,76 @@ impl StreamCollection {
...
+            StreamLayout::Map(..) => Self::Map(Vec::new()),
+        }
+    }
+
     pub fn is_empty(&self) -> bool {
         self.len() == 0
     }
+
+    pub fn consolidate(&mut self) {
+        match self {
```
Comment (mihaibudiu) [inline crates/dataflow-jit/src/ir/literal.rs:99]: let's see if this has problems with NaN.

**Review by mihaibudiu — APPROVED** [review]

File: crates/dataflow-jit/src/codegen/call.rs (hunk 1 above)
Comment (Kixiron) [reply crates/dataflow-jit/src/codegen/call.rs:1268]: I figured, I just don't currently have a way to express that well within the ir, I need aggregate return types of some kind so that I can return a `{ T, bool }` or `{ ?T }`

File: crates/dataflow-jit/src/ir/literal.rs (hunk 2 above)
Comment (Kixiron) [reply crates/dataflow-jit/src/ir/literal.rs:99]: It shouldn't, it calls `Constant`'s comparison impl
